# Generated by Django 4.0.3 on 2022-03-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, null=True)),
                ('option_1', models.CharField(max_length=200, null=True)),
                ('option_2', models.CharField(max_length=200, null=True)),
                ('option_3', models.CharField(max_length=200, null=True)),
                ('option_4', models.CharField(max_length=200, null=True)),
                ('answer', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
