# Generated by Django 4.0.3 on 2022-04-02 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('APP', '0007_alter_quiz_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='attempt',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Attempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examinee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quizname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APP.quiz')),
            ],
        ),
    ]
